# Generated by Django 4.0 on 2022-11-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterwatchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterconsumption',
            old_name='PredictionAccurancy',
            new_name='PredictionAccuracy',
        ),
    ]
