# Generated by Django 2.0.5 on 2018-07-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterwatchapp', '0003_waterconsumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterConsumption',
        ),
    ]
