# Generated by Django 2.0.5 on 2018-07-22 18:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterwatchapp', '0004_delete_waterconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Suburb', models.CharField(max_length=100)),
                ('NoOfSingleResProp', models.IntegerField()),
                ('AvgMonthlyKL', models.IntegerField()),
                ('AvgMonthlyKLPredicted', models.IntegerField()),
                ('PredictionAccruracy', models.IntegerField()),
                ('Month', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('DateTime', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'WaterConsumption',
            },
        ),
    ]
