# Generated by Django 2.0.5 on 2018-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterwatchapp', '0005_waterconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterconsumption',
            name='PredictionAccruracy',
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='PredictionAccuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
